### ISSUE TITLE
Unable to playback Call Recording

### ISSUE THREAD

**Issue by DanBloy** [aws-quickstart/connect-integration-aria#8]
Hi,

I'm getting the following error when loading the tasks for call recording playback

![image](https://user-images.githubusercontent.com/16280675/32984242-be92d8b2-cc9a-11e7-9341-97dfeaf806ed.png)

If i replace **https://eu9.salesforce.com/** with **https://myinstance.awsapps.com/** then the playback works fine in another window. 

Thoughts?

Thanks
Dan

**Comment by KoreyPeters** [comment]
Hi @DanBloy,
Can you confirm the following: Go to Setup -> Develop -> Custom Settings and click on the “Manage” link next to the “Toolkit for Amazon Connect” Custom Setting.
Next, click on the “New” button on the top of the page, which will create the Default Organization values. On the following page, provide the URL to your Amazon Connect instance without any path information. Taking the instance name from the previous examples, the value of for the Url field would be “https://yourinstancename.awsapps.com”.
![image](https://user-images.githubusercontent.com/15987051/33037884-11a8b16a-cdf0-11e7-848a-ef45c0b3d607.png)

**Comment by DanBloy** [comment]
Thanks @KoreyPeters, yep that's set correctly:

![image](https://user-images.githubusercontent.com/16280675/33044288-45f1e5e0-ce40-11e7-8e3b-8c2986b814f9.png)

Could being in the 'eu9' region be an issue?

**Comment by jayyeras** [comment]
Hi @DanBloy, Thank you for the feedback and apologies. We are supporting us-east-1 with this launch.

**Comment by DanBloy** [comment]
Thanks @jayyeras, my CFT was launched within us-east-01 along with my Connect Instance. I don’t believe I can choose where SalesForce installs my tennent (currently eu9). I’ll get a US tennent and re-try.

**Comment by DanBloy** [comment]
hi @jayyeras , I created a new Sf tenant in the US... I get the same result, Unable to play, but the error is different... 

![image](https://user-images.githubusercontent.com/16280675/33152187-4fcab7ce-cfd3-11e7-9b54-69f9dafffd34.png)

![image](https://user-images.githubusercontent.com/16280675/33152234-96136e74-cfd3-11e7-8d18-a455527821d0.png)


Again, the Default Organisation is correctly set (as above). 

Anything i can check?

**Comment by j-fischer** [comment]
Hi @DanBloy,

in the current version, the user must have an active session with Amazon Connect in order to listen to the recording. This can either be achieved by signing in to the CCP softphone within Salesforce, or by signing in to Amazon Connect outside of Salesforce. Could you please confirm if that was the case in your test scenario.  

Please let us know if that did the trick.

**Comment by DanBloy** [comment]
Thanks @j-fischer,

Yes i’ve tried that, both in and out side of Sf. 

Is the URL that Sf trying to pull from correct? Should their be some sort of redirect Managed by Sf? Or would the request be to AWSAPPS? Can you point me to the code that is doing the work here?

**Comment by j-fischer** [comment]
The Visualforce Component that plays the recordings is called ACT_CallRecordingPlayer. 

The key element in this page is the <audio> tag, it takes the Custom Settings value and concatenates it to a full URL. The contact ID is injected as an attribute. In a task's case, it's take from the CallObject standard field. You should be able to take that URL, paste it into a new browser window, and download the recording as an mp3 file. 

Salesforce is not involved in the retrieval of the recording. It only provides the two pieces of data that are needed to build out the recording URL. 

Hope that helps.

**Comment by j-fischer** [comment]
@DanBloy, I found the root cause for the issue that you are experiencing. It's a bug on our end that will be fixed in the next version of the package this week. I am sorry that it took a while, I will post in here when the new version is available, we just need to do some final testing. 

Thanks!

**Comment by DanBloy** [comment]
Awesome 👍 thank you!

**Comment by j-fischer** [comment]
Hi @DanBloy, the new package version (1.4) has been release. The installation links below should allow you to upgrade. Please make sure to select the correct link depending on the environment you are planning to install the Toolkit into. As for the call recording player, assuming that the URL field in the Custom Setting is set correctly, you should be able to see and use the player now. Please make sure to be logged in to Connect, as a session is required to listen to the recordings. 

Hope that will solve your issues. 

Cheers! 

[Install Toolkit v1.4 into Sandbox](https://test.salesforce.com/packaging/installPackage.apexp?p0=04t1I000003YIh4)

[Install Toolkit v1.4 into Production](https://login.salesforce.com/packaging/installPackage.apexp?p0=04t1I000003YIh4)

**Comment by DanBloy** [comment]
Thanks Johannes, upgraded and working great.. really like the fact that it works beyond the native 14days playback that comes with Connect.
